# Evolex Inc Funding File
# Support Evolex Inc's continued development and innovation by contributing.

github: 
  - utkarshkumar

patreon: evolexinc
open_collective: evolexinc
ko_fi: evolexinc

paypal: evolexinc
buymeacoffee: evolexinc
