# Evolex Inc Funding File
# Support Evolex Inc's continued development and innovation by contributing.

github: 
  - utkarshkumar

patreon: https://www.patreon.com/evolexinc
open_collective: https://opencollective.com/evolexinc
ko_fi: https://ko-fi.com/evolexinc

paypal: https://www.paypal.me/evolexinc
buymeacoffee: https://www.buymeacoffee.com/evolexinc
